#!/bin/sh

# dependency: /Users/yumanhordijk/PhD/pi_rotation/MeMe_ADF_distance/5.5/sp.Me1 sp.Me1.results/adf.rkf Me1.rkf
# dependency: /Users/yumanhordijk/PhD/pi_rotation/MeMe_ADF_distance/5.5/sp.Me2 sp.Me2.results/adf.rkf Me2.rkf

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 0.0 -0.0 0.0 region=Me1 adf.f=Me1
        H 0.53644704 -0.92915353 0.0 region=Me1 adf.f=Me1
        H 0.53644704 0.92915353 0.0 region=Me1 adf.f=Me1
        H -1.07289408 -0.0 0.0 region=Me1 adf.f=Me1
        C 0.0 0.000638829 5.5 region=Me2 adf.f=Me2
        H 0.53644704 -0.92915353 5.5 region=Me2 adf.f=Me2
        H 0.53644704 0.92915353 5.5 region=Me2 adf.f=Me2
        H -1.07289408 0.0 5.5 region=Me2 adf.f=Me2
    End
    AllowCloseAtoms Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
         5 6 1.0
         5 7 1.0
         5 8 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization 0.0
    Fragments
        Me1 Me1.rkf 
        Me2 Me2.rkf 
    End
    
    XC
        GGA OLYP
    End
    Symmetry NOSYM
    Unrestricted Yes
    UnrestrictedFragments Yes
EndEngine
eor

