#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 0.0 0.000638829 3.0 region=Me2
        H 0.53644704 -0.92915353 3.0 region=Me2
        H 0.53644704 0.92915353 3.0 region=Me2
        H -1.07289408 0.0 3.0 region=Me2
    End
    Symmetrize Yes
    AllowCloseAtoms Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization -1
    ALLOW  FRACTIONAL
    XC
        GGA OLYP
    End
    Title Me2 fragment
    Symmetry NOSYM
    Unrestricted Yes
EndEngine
eor

